### PR TITLE
FIX IREADY OVERLOAD BRO PLEASE

### PR DESCRIPTION
**Pull request by fortnite2022x**
PLZ FIX IT BRO ITS BEEN PATCHED FOR DAYS NOW AND NOW U RELEASED A JOKE VERSION ON UR DISCORD? I HAVE LESSONS TO COMPLETE UMM
unknown
?

### CODE REVIEW

**Comment by nevadex** [comment]
LMFAOO YOU ACTUALLY LOST UR ACC

**Comment by DJ-Banz77** [comment]
Guys please fix it I really need it

**Comment by derinpilge** [comment]
LMAOOOO

**Comment by derinpilge** [comment]
type in the joke version script; i wanna get my account delete

**Comment by Thejakster92k** [comment]
he didnt actual get banned... if he closes the extension and reloads and opens up developer menu it wont close his account for failed terms of use

**Comment by marshmellow987** [comment]
fix it please

**Comment by epicgamer3819** [comment]
please fix

**Comment by Prcsper** [comment]
please fix it and read the thing where it automatically does ur lesson, having to look at another tab back and forth answering questions is annoying plus all of the answers dont show

**Comment by LolMakesStuff** [comment]
Ok guys, please note that since the iready devs are patching overload, cupid is probably trying to fix this, plus, even if you do use overload, **iready has a logger for overload and reports the user who uses it to their teacher.** Because of this logger, this patch will take a while, so please wait everyone!

**Comment by Prcsper** [comment]
> Ok guys, please note that since the iready devs are patching overload, cupid is probably trying to fix this, plus, even if you do use overload, **iready has a logger for overload and reports the user who uses it to their teacher.** Because of this logger, this patch will take a while, so please wait everyone!

how do you know it has a logger and sends it to their teachers?

**Comment by asteen08** [comment]
> > Ok guys, please note that since the iready devs are patching overload, cupid is probably trying to fix this, plus, even if you do use overload, **iready has a logger for overload and reports the user who uses it to their teacher.** Because of this logger, this patch will take a while, so please wait everyone!
> 
> how do you know it has a logger and sends it to their teachers?

i-Ready E-Mailed my school that they "flagged" my i-Ready account and administrators told me there has been this "Tik-Tok hack on how to cheat and boost scores on i-Ready but I told them that my account has been stolen by somebody.

**Comment by CodeSalvageON** [comment]
tried to fix some of the patches.
https://github.com/CodeSalvageON/Dead-Channel
Basically it can only skip animations, however it does have autoclicker for minutes and a whole graphing calculator

**Comment by Prcsper** [comment]
> > > Ok guys, please note that since the iready devs are patching overload, cupid is probably trying to fix this, plus, even if you do use overload, **iready has a logger for overload and reports the user who uses it to their teacher.** Because of this logger, this patch will take a while, so please wait everyone!
> > 
> > 
> > how do you know it has a logger and sends it to their teachers?
> 
> i-Ready E-Mailed my school that they "flagged" my i-Ready account and administrators told me there has been this "Tik-Tok hack on how to cheat and boost scores on i-Ready but I told them that my account has been stolen by somebody.

I've been smart with my thing but I've done most of my lessons legit so I think I'll be alright. I just cannot stand math

**Comment by xpprofessional08** [comment]
I was being smart with it too, not using it on my school computer, not
using while patched, and always updating to latest version.

**Comment by blunteryeti208** [comment]
> PLZ FIX IT BRO ITS BEEN PATCHED FOR DAYS NOW AND NOW U RELEASED A JOKE VERSION ON UR DISCORD? I HAVE LESSONS TO COMPLETE UMM unknown ?

BRO DISCORD DOESNT WORK ON SCHOOL COMPUTORS PLEASE UPDATE IT ON GITHUB PLEASEEEEEEE

**Comment by blunteryeti208** [comment]
IM REALLY UPSET THE FACT THAT I CANT USE THE HACK ANYMORE PLEASE UPDATE IT ON GITHUB

**Comment by Gam3rrXD** [comment]
Bro stfu its discord only because it keeps getting patched, If your too lazy to find a way to get discord that's your problem

**Comment by george0513** [comment]
disc link not working

**Comment by ianfreya1** [comment]
plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz FIX THIS ALREADY DISCORD IS BLOCKED 4 ME I NEED IREADY OVERLOAD SAVE ME

**Comment by ianfreya1** [comment]
fix it now

**Comment by ianfreya1** [comment]
fix it

**Comment by ianfreya1** [comment]
plz

**Comment by GhostNovaaa** [comment]
Ok, you idiots You go to croxyproxy and download it from there. That's how you get it.

> PLZ FIX IT BRO ITS BEEN PATCHED FOR DAYS NOW AND NOW U RELEASED A JOKE VERSION ON UR DISCORD? I HAVE LESSONS TO COMPLETE UMM unknown ?

**Comment by ianfreya1** [comment]
> 

bruh it is croxyproxy is blocked

**Comment by GhostNovaaa** [comment]
Hey guess what? HE UPDATED IT.

**Comment by ianfreya1** [comment]
where is the bookmarklet? i cant find it and my school blocked any addons to chrome

**Pull request closed without merging**
