### PR TITLE
Fix the FKN hack kiddo.

### PR DESCRIPTION
**Pull request by firevpn1**
Still having trouble fixing it? LOOOL. You stole all the code from the original creator. You can't code at all kiddo. I would be suprised if you could even understand what console.log() does. Fix the code kiddo, you'll never fix it, considering you have 0.5 braincells.

### CODE REVIEW

**Comment by 31KR** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by cupiditys** [comment]
i turned off issues and bro went to the pull requests :skull: :skull: :skull: :skull: :skull:

**Comment by cupiditys** [comment]
also ur pretty obviously joking

**Comment by kkxninja** [comment]
may you please help me update it bc it wont let me i have version 16
someone in my school payed my 25$ to do all there iready and my version is not working
i really need help

**Comment by hattenwastaken** [comment]
> may you please help me update it bc it wont let me i have version 16 someone in my school payed my 25$ to do all there iready and my version is not working i really need help

better get to iready

**Comment by Wang-sus** [comment]
Kiddo

**Comment by KillaNAdev** [comment]
> > may you please help me update it bc it wont let me i have version 16 someone in my school payed my 25$ to do all there iready and my version is not working i really need help
> 
> better get to iready

man that's what I am saying

**Comment by goldbeg** [comment]
> Still having trouble fixing it? LOOOL. You stole all the code from the original creator. You can't code at all kiddo. I would be suprised if you could even understand what console.log() does. Fix the code kiddo, you'll never fix it, considering you have 0.5 braincells.

cant tell if your jokking or not

**Pull request closed without merging**
